Repository interlegis/sapl, pull requests merged in 2019-05, with the labels that each got.

#2762 Refatora título
  sapl/templates/navbar.yaml
Labels: bug

#2752 Fix #2751 e Automatiza a alteração do campo "Em Tramitação?" das Matérias Legislativas
  sapl/materia/forms.py
  sapl/materia/tests/test_materia.py
  sapl/materia/views.py
Labels: bug, ideia

#2757 Fix #2754 - Tramita os documentos anexados ao DocAdm principal
  sapl/materia/forms.py
  sapl/protocoloadm/forms.py
  sapl/protocoloadm/views.py
Labels: bug

#2769 Fix #2767 - Ocultar título Matérias da Ordem do dia quando não existem matérias
  sapl/templates/sessao/blocos_ata/lista_presenca.html
  sapl/templates/sessao/blocos_ata/materias_expediente.html
  sapl/templates/sessao/blocos_ata/materias_ordem_dia.html
  sapl/templates/sessao/blocos_ata/mesa_diretora.html
  sapl/templates/sessao/blocos_ata/ocorrencias_da_sessao.html
  sapl/templates/sessao/blocos_ata/oradores_expediente.html
  sapl/templates/sessao/blocos_ata/oradores_explicacoes.html
Labels: bug

#2765 Fix #2763 - Edita e remove tramitacões anexadas se possível
  sapl/materia/forms.py
  sapl/materia/tests/test_materia.py
  sapl/materia/views.py
  sapl/protocoloadm/forms.py
  sapl/protocoloadm/tests/test_protocoloadm.py
  sapl/protocoloadm/views.py
  sapl/utils.py
Labels: bug

#2713 Script para remover multiplos parlamentares
  sapl/parlamentares/forms.py
  scripts/deduplica_parlamentares.py
Labels: bug

#2791 Adiciona opção de selecionar todos na busca textual
  sapl/templates/search/search.html
Labels: ideia

#2773 #2764 - Cria tramitação em Lote para Documento Administrativo
  sapl/materia/views.py
  sapl/protocoloadm/forms.py
  sapl/protocoloadm/tests/test_protocoloadm.py
  sapl/protocoloadm/urls.py
  sapl/protocoloadm/views.py
  sapl/templates/navbar.yaml
  sapl/templates/protocoloadm/em_lote/subnav_em_lote.yaml
  sapl/templates/protocoloadm/em_lote/tramitacaoadm.html
Labels: ideia

#2785 Fix #2783 - Retirada de pauta não seta votacao_aberta para False
  sapl/sessao/forms.py
Labels: bug, prioridade alta

#2787 Fix #2786 - Votar uma matéria Em Bloco mesmo que tenha sido retirada de pauta
  sapl/sessao/views.py
  sapl/templates/sessao/votacao/votacao_bloco_expediente.html
  sapl/templates/sessao/votacao/votacao_bloco_ordem.html
Labels: bug, prioridade alta

#2772 Adiciona aviso quando expediente não tem conteúdo
  sapl/templates/sessao/blocos_ata/expedientes.html
Labels: bug, ideia

#2789 Fix #2788 e Fix #2790
  sapl/sessao/forms.py
Labels: bug

#2778 Adicionar Pauta Reunião
  sapl/comissoes/forms.py
  sapl/comissoes/urls.py
  sapl/comissoes/views.py
  sapl/materia/migrations/0049_pautareuniao.py
  sapl/materia/models.py
  sapl/materia/views.py
  sapl/protocoloadm/views.py
  sapl/rules/map_rules.py
  sapl/templates/comissoes/pauta.html
  sapl/templates/comissoes/reuniao_detail.html
Labels: ideia

#2800 HOT-FIX: Evita quebra em Resumo da sessão devido à ordenação
  sapl/sessao/tests/test_sessao_view.py
  sapl/sessao/views.py
Labels: ideia

#2803 Cria Relatorio de Tramitacões para Documento Administrativo
  sapl/base/forms.py
  sapl/base/urls.py
  sapl/base/views.py
  sapl/templates/base/RelatorioHistoricoTramitacaoAdm_filter.html
  sapl/templates/base/relatorios_list.html
Labels: ideia

#2795 Fix #2794 - Relatório de tramitações
  sapl/base/forms.py
  sapl/base/views.py
  sapl/templates/base/RelatorioDataFimPrazoTramitacao_filter.html
  sapl/templates/base/RelatorioHistoricoTramitacao_filter.html
  sapl/templates/base/relatorios_list.html
Labels: ideia

#2814 #2812 - Possibilita parlamentares não presentes na ordem do dia a serem oradores
  sapl/sessao/forms.py
Labels: bug

#2813 #2807 - Criação de migração para aplicar valores válidos e únicos em ResumoOrdem
  sapl/sessao/migrations/0040_auto_20190523_1130.py
Labels: bug

#2820 HOT-FIX: Retira duplicação da classe Orador
  sapl/sessao/views.py
Labels: bug

#2821 Fix #2818 - Oculta informações do resumo
  sapl/relatorios/templates/pdf_sessao_plenaria_gerar.py
  sapl/templates/sessao/blocos_resumo/conteudo_multimidia.html
  sapl/templates/sessao/blocos_resumo/expedientes.html
  sapl/templates/sessao/blocos_resumo/identificacao_basica.html
  sapl/templates/sessao/blocos_resumo/lista_presenca.html
  sapl/templates/sessao/blocos_resumo/lista_presenca_ordem_dia.html
  sapl/templates/sessao/blocos_resumo/materias_expediente.html
  sapl/templates/sessao/blocos_resumo/materias_ordem_dia.html
  sapl/templates/sessao/blocos_resumo/mesa_diretora.html
  sapl/templates/sessao/blocos_resumo/ocorrencias_da_sessao.html
  sapl/templates/sessao/blocos_resumo/oradores_expediente.html
  sapl/templates/sessao/blocos_resumo/oradores_explicacoes.html
  sapl/templates/sessao/blocos_resumo/oradores_ordemdia.html
  sapl/templates/sessao/blocos_resumo/votos_nominais_materias_expediente.html
  sapl/templates/sessao/blocos_resumo/votos_nominais_materias_ordem_dia.html
  sapl/templates/sessao/resumo.html
Labels: ideia

#2810 #2805 - Tramitação de anexadas como opcional
  sapl/base/forms.py
  sapl/base/migrations/0037_auto_20190527_0901.py
  sapl/base/models.py
  sapl/materia/forms.py
  sapl/materia/tests/test_materia.py
  sapl/materia/views.py
  sapl/protocoloadm/forms.py
  sapl/protocoloadm/tests/test_protocoloadm.py
  sapl/protocoloadm/views.py
  sapl/templates/base/layouts.yaml
Labels: ideia

#2799 Fix #2798
  sapl/materia/forms.py
  sapl/materia/views.py
Labels: bug

#2608 Fix #2161 - Alteração de nome de Partido
  sapl/base/forms.py
  sapl/parlamentares/migrations/0023_auto_20180626_1524.py
  sapl/parlamentares/migrations/0026_bloco.py
  sapl/parlamentares/migrations/0027_auto_20190430_0839.py
  sapl/parlamentares/migrations/0027_auto_20190517_1050.py
  sapl/parlamentares/migrations/0028_auto_20190515_1744.py
  sapl/parlamentares/models.py
  sapl/parlamentares/urls.py
  sapl/parlamentares/views.py
  sapl/rules/map_rules.py
  sapl/sessao/views.py
  sapl/templates/parlamentares/partido_detail.html
  sapl/templates/parlamentares/partido_update.html
  sapl/utils.py
Labels: ideia

#2823 Correção na descrição no título dos tipos de textos
  sapl/templates/compilacao/subnav.html
  sapl/templates/norma/subnav.yaml
Labels: bug

#2824 HOT-FIX Arrumando cronologia das migrations
  sapl/parlamentares/migrations/0028_auto_20190515_1744.py
  sapl/parlamentares/migrations/0030_auto_20190531_0848.py
Labels: bug
