Repository interlegis/sapl, pull requests merged in 2019-04, with the labels that each got.

#2674 Fix #2665 - Tramitar matérias anexadas junto com as matérias anexadoras
  sapl/materia/views.py
Labels: bug

#2673 Fix #2671
  sapl/sessao/forms.py
  sapl/sessao/views.py
Labels: bug

#2677 Fix #2653 - Mostra parlamentares de período escolhido em relatoria
  sapl/comissoes/urls.py
  sapl/comissoes/views.py
  sapl/materia/forms.py
  sapl/materia/tests/test_materia_form.py
  sapl/materia/views.py
  sapl/templates/materia/relatoria_form.html
Labels: ideia

#2579 Fix #2536 - Separa criação de mandato e parlamentar
  sapl/parlamentares/forms.py
  sapl/parlamentares/urls.py
  sapl/parlamentares/views.py
  sapl/templates/parlamentares/layouts.yaml
  sapl/templates/parlamentares/parlamentar_filter.html
  sapl/templates/parlamentares/parlamentares_list.html
  sapl/templates/parlamentares/vincular_parlamentar.html
Labels: arquitetura, bug, estrutural, ideia

#2662 Fix #2403 Adiciona Oradores da Ordem do Dia
  sapl/relatorios/templates/pdf_sessao_plenaria_gerar.py
  sapl/relatorios/views.py
  sapl/rules/map_rules.py
  sapl/sessao/forms.py
  sapl/sessao/migrations/0034_oradorordemdia.py
  sapl/sessao/migrations/0035_resumoordenacao_decimo_quarto.py
  sapl/sessao/models.py
  sapl/sessao/urls.py
  sapl/sessao/views.py
  sapl/templates/relatorios/relatorio_ata.html
  sapl/templates/sessao/blocos_ata/oradores_ordemdia.html
  sapl/templates/sessao/blocos_resumo/oradores_ordemdia.html
  sapl/templates/sessao/layouts.yaml
  sapl/templates/sessao/resumo.html
  sapl/templates/sessao/resumo_ata.html
  sapl/templates/sessao/subnav.yaml
Labels: ideia

#2697 Adiciona botão Adicionar Parlamentar em Tabelas Auxiliares
  sapl/templates/menu_tabelas_auxiliares.yaml
Labels: ideia

#2699 Corrige problema ao enviar anexo de norma jurídica
  sapl/norma/forms.py
  sapl/norma/models.py
Labels: bug

#2716 Adiciona campo regime tramitação como obrigatório
  sapl/materia/forms.py
Labels: bug

#2630 Implementa opções de anexar em Documentos Administrativos
  sapl/api/views.py
  sapl/materia/views.py
  sapl/protocoloadm/forms.py
  sapl/protocoloadm/migrations/0018_auto_20190314_1532.py
  sapl/protocoloadm/models.py
  sapl/protocoloadm/urls.py
  sapl/protocoloadm/views.py
  sapl/rules/map_rules.py
  sapl/sessao/migrations/0036_auto_20190409_1452.py
  sapl/sessao/migrations/0037_merge_20190411_1548.py
  sapl/templates/protocoloadm/anexado_list.html
  sapl/templates/protocoloadm/em_lote/anexado.html
  sapl/templates/protocoloadm/layouts.yaml
  sapl/templates/protocoloadm/subnav.yaml
Labels: ideia

#2727 Adiciona IP e User em VotoParlamentar e RegistroVotacao
  sapl/sessao/migrations/0037_auto_20190415_1324.py
  sapl/sessao/models.py
  sapl/sessao/views.py
Labels: bug

#2726 HOT-FIX: Reordena as configurações para melhorar o visual
  sapl/templates/base/layouts.yaml
Labels: ideia

#2715 Script para remover multiplos autores
  scripts/remove_multiplos_autores.py
Labels: bug

#2725 Fix #2711 - Adiciona opção de numeração de Tramitação por ano independentemente do autor
  sapl/base/migrations/0033_auto_20190415_1050.py
  sapl/base/models.py
  sapl/materia/forms.py
  sapl/materia/migrations/0045_auto_20190415_1050.py
Labels: ideia

#2724 Verifica se a Sessão está aberta ou finalizada na Votacão em Bloco
  sapl/sessao/views.py
  sapl/templates/sessao/votacao/votacao_bloco_expediente.html
  sapl/templates/sessao/votacao/votacao_bloco_ordem.html
Labels: bug

#2707 Fix #2672 Adiciona formatação alternativa de entrada para data de publicação e efetividade
  sapl/compilacao/forms.py
Labels: compilação

#2735 HOT-FIX: Reordena as configurações do cronômetro para melhorar o visual
  sapl/templates/base/layouts.yaml
Labels: ideia

#2714 Fix #2712 Ocorrencias de partido atual em extrato e resumo.
  sapl/templates/relatorios/relatorio_ata.html
  sapl/templates/sessao/blocos_ata/assinaturas.html
  sapl/templates/sessao/blocos_ata/lista_presenca.html
  sapl/templates/sessao/blocos_ata/lista_presenca_ordem_dia.html
  sapl/templates/sessao/blocos_ata/mesa_diretora.html
  sapl/templates/sessao/blocos_ata/oradores_expediente.html
  sapl/templates/sessao/blocos_ata/oradores_explicacoes.html
  sapl/templates/sessao/blocos_resumo/lista_presenca_ordem_dia.html
  sapl/templates/sessao/blocos_resumo/mesa_diretora.html
  sapl/templates/sessao/blocos_resumo/oradores_explicacoes.html
Labels: bug

#2704 Fix #2700 Corrige Duplicação em PDF de Resumo de Sessão
  sapl/sessao/forms.py
  sapl/sessao/migrations/0037_auto_20190415_1635.py
  sapl/sessao/migrations/0038_merge_20190415_1800.py
  sapl/sessao/models.py
  sapl/sessao/views.py
Labels: bug

#2733 Fix #2711 e erro introduzido no commit 7f90bd7 - Numeração de Proposições e Protocolos
  sapl/base/forms.py
  sapl/base/migrations/0034_auto_20190417_0941.py
  sapl/base/migrations/0035_auto_20190417_1009.py
  sapl/base/migrations/0036_auto_20190417_1432.py
  sapl/base/models.py
  sapl/materia/forms.py
  sapl/materia/migrations/0046_auto_20190417_0941.py
  sapl/materia/migrations/0047_auto_20190417_1432.py
  sapl/materia/models.py
  sapl/templates/base/layouts.yaml
Labels: bug, prioridade alta

#2750 Fix #2742 - BugFix ordenar normas relacionadas
  sapl/norma/migrations/0024_auto_20190425_0917.py
  sapl/norma/models.py
Labels: bug

#2736 Fix #2720 - Adiciona usuários às tramitações
  sapl/materia/forms.py
  sapl/materia/migrations/0046_auto_20190417_1212.py
  sapl/materia/migrations/0048_merge_20190426_0828.py
  sapl/materia/models.py
  sapl/materia/views.py
  sapl/protocoloadm/forms.py
  sapl/protocoloadm/migrations/0019_auto_20190426_0833.py
  sapl/protocoloadm/models.py
  sapl/protocoloadm/tests/test_protocoloadm.py
  sapl/protocoloadm/views.py
  sapl/templates/materia/tramitacao_detail.html
  sapl/templates/protocoloadm/tramitacaoadministrativo_detail.html
Labels: ideia

#2755 Fix #2753 - Corrige inconsistências entre Tramitacao DocAdm e MateriaLegislativa
  sapl/materia/views.py
  sapl/protocoloadm/forms.py
  sapl/protocoloadm/migrations/0019_auto_20190429_0828.py
  sapl/protocoloadm/migrations/0020_tramitacaoadministrativo_timestamp.py
  sapl/protocoloadm/models.py
  sapl/protocoloadm/tests/test_protocoloadm.py
  sapl/protocoloadm/views.py
  sapl/templates/protocoloadm/layouts.yaml
Labels: bug
