Repository interlegis/sapl, pull requests merged in 2019-03, with the labels that each got.

#2593 Reverte separação de criação da vinculação do parlamentar
  sapl/parlamentares/forms.py
  sapl/parlamentares/tests/test_parlamentares.py
  sapl/parlamentares/urls.py
  sapl/parlamentares/views.py
  sapl/templates/menu_tabelas_auxiliares.yaml
  sapl/templates/parlamentares/layouts.yaml
  sapl/templates/parlamentares/lista_parlamentares.html
  sapl/templates/parlamentares/parlamentares_list.html
Labels: estrutural

#2577 Correções solicitadas no pull request #2567
  sapl/parlamentares/views.py
  sapl/templates/parlamentares/partido_filiados.html
Labels: ideia

#2606 HOT-FIX: Adicionar exceção para quando a configuração da ordenação estiver incorreta
  sapl/sessao/views.py
Labels: bug

#2540 Selecionar parlamentar para relatoria do período da matéria
  sapl/materia/forms.py
  sapl/materia/views.py
Labels: ideia

#2620 HOT-FIX: Fix botões de Marcar/Desmarcar todos
  sapl/templates/materia/em_lote/acessorio.html
  sapl/templates/materia/em_lote/anexada.html
  sapl/templates/materia/em_lote/tramitacao.html
  sapl/templates/sessao/votacao/votacao_bloco_expediente.html
  sapl/templates/sessao/votacao/votacao_bloco_ordem.html
Labels: bug

#2622 Fix #2621 - Subnav não aparecendo
  sapl/sessao/views.py
  sapl/templates/sessao/adicionar_varias_materias_expediente.html
  sapl/templates/sessao/adicionar_varias_materias_ordem.html
Labels: bug

#2624 Resolve problema do batch_size na request
  sapl/lexml/OAIServer.py
  sapl/lexml/views.py
Labels: bug

#2601 Fix #2599 - Atividade Legislativa Impressos
  sapl/materia/forms.py
  sapl/materia/urls.py
  sapl/materia/views.py
  sapl/norma/forms.py
  sapl/norma/views.py
  sapl/protocoloadm/views.py
  sapl/templates/materia/impressos/ficha.html
  sapl/templates/materia/impressos/ficha_seleciona.html
  sapl/templates/materia/impressos/impressos.html
  sapl/templates/materia/impressos/impressos_form.html
  sapl/templates/materia/impressos/materias_pdf.html
  sapl/templates/materia/impressos/norma.html
  sapl/templates/materia/impressos/normas_pdf.html
Labels: ideia

#2637 Corrige erro na paginação no LexML
  sapl/lexml/OAIServer.py
Labels: bug

#2664 Fix Documento Acessório em Lote para Arquivos Grandes
  sapl/materia/migrations/0044_auto_20190327_1409.py
  sapl/materia/models.py
  sapl/materia/views.py
Labels: bug
