Repository interlegis/sapl, pull requests merged in 2019-08, with the labels that each got.

#2901 Relatorio de Documentos Acessórios de Matéria Legislativa
  sapl/base/forms.py
  sapl/base/urls.py
  sapl/base/views.py
  sapl/templates/base/RelatorioDocumentosAcessorios_filter.html
  sapl/templates/base/relatorios_list.html
Labels: ideia

#2894 Sincronização de cronômetros em diferentes máquinas
  sapl/base/templatetags/common_tags.py
  sapl/painel/migrations/0010_auto_20190711_1030.py
  sapl/painel/migrations/0011_cronometro_last_stop_duration.py
  sapl/painel/models.py
  sapl/painel/views.py
  sapl/sessao/views.py
  sapl/templates/painel/index.html
  sapl/templates/sessao/painel.html
Labels: painel

#2932 Fix Chamado #326247
  sapl/comissoes/forms.py
Labels: bug

#2916 Fix #2915 - Adiciona informação de Data Fim Prazo de Tramitação
  sapl/templates/comissoes/materias_em_tramitacao.html
Labels: ideia

#2938 Fix #2931 - Buscar Matérias Legislativas por campos de origem externa
  sapl/materia/forms.py
  sapl/materia/views.py
Labels: ideia

#2923 Fix #2920 - Campo de ordenação em TipoExpediente
  sapl/sessao/migrations/0045_auto_20190809_1319.py
  sapl/sessao/migrations/0046_auto_20190809_1319.py
  sapl/sessao/models.py
  sapl/sessao/views.py
  sapl/templates/sessao/layouts.yaml
Labels: ideia

#2904 Fix #2903 #1373 - Afastamento de Parlamentar
  sapl/base/views.py
  sapl/parlamentares/forms.py
  sapl/parlamentares/migrations/0033_afastamentoparlamentar.py
  sapl/parlamentares/migrations/0034_auto_20190801_1408.py
  sapl/parlamentares/migrations/0035_merge_20190802_0954.py
  sapl/parlamentares/models.py
  sapl/parlamentares/tests/test_parlamentares.py
  sapl/parlamentares/urls.py
  sapl/parlamentares/views.py
  sapl/rules/map_rules.py
  sapl/sessao/forms.py
  sapl/sessao/views.py
  sapl/templates/base/RelatorioPresencaSessao_filter.html
  sapl/templates/parlamentares/layouts.yaml
  sapl/templates/parlamentares/subnav.yaml
  sapl/templates/parlamentares/tipoafastamento_form.html
  sapl/templates/sessao/presenca.html
  sapl/templates/sessao/presenca_ordemdia.html
  sapl/utils.py
Labels: ideia

#2922 Fix #2913 - Painel eletrônico modular
  sapl/painel/urls.py
  sapl/painel/views.py
  sapl/templates/painel/index.html
  sapl/templates/sessao/painel.html
Labels: ideia, painel
