Repository interlegis/sapl, pull requests merged in 2019-07, with the labels that each got.

#2868 Fix #2867 - Altera valores na url de matéria para autor
  sapl/templates/parlamentares/materias.html
Labels: bug

#2870 Retira trava de ano e data de apresentação diferentes em Norma e Matéria
  sapl/materia/forms.py
  sapl/norma/forms.py
  sapl/templates/materia/materialegislativa_form.html
  sapl/templates/norma/normajuridica_form.html
Labels: ideia

#2863 Refatoração de Tramitação em Lote
  sapl/materia/forms.py
  sapl/materia/views.py
  sapl/protocoloadm/views.py
  sapl/templates/materia/em_lote/tramitacao.html
Labels: refatoração

#2862 Fix #2660 - Esconde última votacão quando sessão é finalizada
  sapl/painel/views.py
  sapl/templates/painel/index.html
Labels: ideia, painel

#2861 Fix #1782 - Cronômetro da Questão de Ordem trava os demais
  sapl/painel/forms.py
  sapl/painel/migrations/0003_auto_20190603_1033.py~HEAD
  sapl/painel/migrations/0004_auto_20190603_1033.py~HEAD
  sapl/painel/migrations/0005_painelconfig.py
  sapl/painel/models.py
  sapl/painel/urls.py
  sapl/painel/views.py
  sapl/rules/map_rules.py
  sapl/sessao/views.py
  sapl/templates/menu_tabelas_auxiliares.yaml
  sapl/templates/painel/layouts.yaml
  sapl/templates/painel/painelconfig_form.html
  sapl/templates/sessao/painel.html
Labels: painel

#2875 Fix #2872 - Adiciona User e IP em NormaJuridica
  sapl/materia/views.py
  sapl/norma/forms.py
  sapl/norma/migrations/0025_auto_20190704_1403.py
  sapl/norma/models.py
  sapl/norma/views.py
  sapl/templates/norma/normajuridica_detail.html
Labels: ideia

#2871 Fix #2749 - Configurar cronômetro - tempo de disparo e com que antecedência
  sapl/painel/forms.py
  sapl/painel/migrations/0003_auto_20190603_1033.py~HEAD
  sapl/painel/migrations/0004_auto_20190603_1033.py~HEAD
  sapl/painel/migrations/0006_auto_20190612_1347.py
  sapl/painel/migrations/0007_painelconfig_tempo_disparo_termino.py
  sapl/painel/models.py
  sapl/templates/painel/index.html
  sapl/templates/painel/layouts.yaml
  sapl/templates/painel/painelconfig_form.html
  sapl/templates/sessao/painel.html
Labels: painel

#2881 Adiciona opção de exibir nome da Casa Legislativa no painel
  sapl/painel/forms.py
  sapl/painel/migrations/0008_painelconfig_exibir_nome_casa.py
  sapl/painel/models.py
  sapl/painel/views.py
  sapl/templates/painel/index.html
  sapl/templates/painel/layouts.yaml
Labels: ideia

#2882 Fix #2052 - Cria opção de mostrar os votos no painel durante votação
  sapl/painel/forms.py
  sapl/painel/migrations/0009_painelconfig_mostrar_votos_antecedencia.py
  sapl/painel/models.py
  sapl/painel/views.py
  sapl/templates/painel/index.html
  sapl/templates/painel/layouts.yaml
Labels: painel

#2883 Fix #1556 - Salvar um registro prévio com os Votos dos Parlamentares
  sapl/painel/views.py
  sapl/sessao/urls.py
  sapl/sessao/views.py
  sapl/templates/painel/index.html
  sapl/templates/painel/voto_nominal.html
  sapl/templates/sessao/votacao/nominal.html
Labels: painel

#2876 Fix #1598 - Adiciona checkbox na criação de Despacho Inicial de Matérias
  sapl/materia/forms.py
  sapl/materia/migrations/0051_auto_20190703_1414.py
  sapl/materia/models.py
  sapl/materia/urls.py
  sapl/materia/views.py
  sapl/templates/materia/despachoinicial_multicreate_form.html
Labels: ideia

#2888 Corrigindo novo relatório sessão plenária Fix #2887
  sapl/static/sapl/css/relatorio.css
  sapl/templates/relatorios/header_ata.html
  sapl/templates/relatorios/relatorio_doc_administrativos.html
  sapl/templates/relatorios/relatorio_sessao_plenaria.html
Labels: bug

#2900 Fix Chamado #512315 - Relatório de Presenças
  sapl/base/forms.py
  sapl/base/views.py
  sapl/templates/base/RelatorioPresencaSessao_filter.html
Labels: ideia
