Repository interlegis/sapl, pull requests merged in 2019-10, with the labels that each got.

#2994 Arrumando apresentação de expedientes em pauta sessão
  sapl/sessao/views.py
  sapl/templates/sessao/pauta_sessao_detail.html
Labels: bug

#3003 Fix #2691 - Exclusão de Arquivos
  sapl/audiencia/models.py
  sapl/comissoes/models.py
  sapl/materia/models.py
  sapl/norma/models.py
  sapl/protocoloadm/models.py
  sapl/sessao/models.py
Labels: bug

#2965 Ajusta a performance da lista de Matérias em Tramitação em uma Comissão
  sapl/comissoes/views.py
  sapl/templates/comissoes/materias_em_tramitacao.html
Labels: qualidade, refatoração, usabilidade

#2957 Fix #2933 - Adiciona tabela auxiliar para Turno de Tramitações
  sapl/materia/forms.py
  sapl/materia/migrations/0060_auto_20190905_1134.py
  sapl/materia/migrations/0061_auto_20190905_1135.py
  sapl/materia/migrations/0062_remove_tramitacao_turno.py
  sapl/materia/models.py
  sapl/materia/urls.py
  sapl/materia/views.py
  sapl/relatorios/views.py
  sapl/rules/map_rules.py
  sapl/sessao/views.py
  sapl/templates/materia/layouts.yaml
  sapl/templates/menu_tabelas_auxiliares.yaml
  sapl/templates/sessao/blocos_resumo/materias_ordem_dia.html
  sapl/templates/sessao/votacao/votacao_bloco.html
Labels: ideia

#3010 Fix #3011 - Adicionar Matérias à Pauta
  sapl/comissoes/forms.py
  sapl/comissoes/views.py
  sapl/materia/forms.py
  sapl/materia/views.py
  sapl/templates/comissoes/pauta.html
  sapl/templates/comissoes/reuniao_detail.html
  sapl/templates/materia/em_lote/anexada.html
Labels: bug, prioridade alta
