Repository interlegis/sapl, pull requests merged in 2020-04, with the labels that each got.

#3135 Fix #3134 - Aumenta o tamanho máximo da sigla de um partido
  sapl/parlamentares/migrations/0031_auto_20200407_1406.py
  sapl/parlamentares/models.py
Labels: bug

#3132 3104 - Ordenação das matérias da ordem do dia
  sapl/sessao/urls.py
  sapl/sessao/views.py
  sapl/templates/sessao/expedientemateria_list.html
  sapl/templates/sessao/ordemdia_list.html
Labels: ideia

#3141 Fix #3140 - Capacidade dos Campos de IP
  sapl/materia/migrations/0067_auto_20200416_1538.py
  sapl/materia/models.py
  sapl/norma/migrations/0033_auto_20200416_1538.py
  sapl/norma/models.py
  sapl/protocoloadm/migrations/0032_auto_20200416_1538.py
  sapl/protocoloadm/models.py
  sapl/sessao/migrations/0051_auto_20200416_1538.py
  sapl/sessao/models.py
Labels: bug, prioridade alta

#3146 751191 - Ordenação de Mesa Diretora em relatório PDF
  sapl/relatorios/views.py
Labels: bug

#3150 Fix #3148 - Adequando paginação de legislatura na pagina de parlamentares
  sapl/api/pagination.py
Labels: bug
