Repository interlegis/sapl, pull requests merged in 2020-06, with the labels that each got.

#3164 3081 - Campos rotulo_prefixo_texto e rotulo_sufixo_texto como somente leitura
  sapl/compilacao/admin.py
Labels: bug

#3133 Script para restauração da base de dados
  .gitignore
  scripts/restore_db.sh
Labels: bug, ideia

#3171 Adiciona exclusão de composição
  sapl/comissoes/migrations/0025_auto_20200605_1051.py
  sapl/comissoes/models.py
  sapl/comissoes/views.py
  sapl/templates/comissoes/composicao_list.html
Labels: bug

#3185 3181 - Ementa da matéria no painel eletrônico
  sapl/painel/views.py
  sapl/templates/painel/index.html
Labels: bug

#3008 2978 - Audiência Pública com Parlamentar Autor e Requerimento
  sapl/audiencia/forms.py
  sapl/audiencia/migrations/0015_auto_20200518_1158.py
  sapl/audiencia/models.py
  sapl/templates/audiencia/layouts.yaml
Labels: ideia

#3180 Adiciona campo de observação de orador expediente em relatório PDF
  sapl/templates/relatorios/blocos_sessao_plenaria/oradores_expediente.html
Labels: bug

#3192 Fix #3191 - Corrigindo erro em comissao
  sapl/comissoes/forms.py
Labels: bug

#3193 Remove barra desnecessária no final do link
  sapl/base/urls.py
Labels: bug

#3204 Classificações de logs
  sapl/audiencia/forms.py
  sapl/base/forms.py
  sapl/comissoes/forms.py
  sapl/crud/base.py
Labels: refatoração

#3196 3177 - Adiciona Pesquisa de Autor
  sapl/base/forms.py
  sapl/base/urls.py
  sapl/base/views.py
  sapl/templates/base/autor_detail.html
  sapl/templates/base/autor_filter.html
  sapl/templates/menu_tabelas_auxiliares.yaml
Labels: bug

#3212 Fix #3211 - Validação de Criação e Edição de Autores
  sapl/base/forms.py
Labels: bug

#3199 Corrigindo logs
  sapl/api/serializers.py
  sapl/materia/views.py
  sapl/norma/forms.py
  sapl/norma/views.py
Labels: bug, refatoração
