Repository interlegis/sapl, pull requests merged in 2020-03, with the labels that each got.

#3071 Docker para desenvolvimento
  Dockerfile.dev
  docker-compose-dev.yml
Labels: ambiente

#3122 Chamado 273957 - Nome e Sobrenome na edição de Usuário
  sapl/base/forms.py
  sapl/base/views.py
Labels: bug

#3125 Fiz #3114 - Adiciona ordenação de Assunto Matéria por ordem alfabética
  sapl/materia/migrations/0065_auto_20200313_1137.py
  sapl/materia/models.py
Labels: ideia

#3118 Fix #3117 - Filtra as coligações no cadastro de Mandato
  sapl/parlamentares/urls.py
  sapl/parlamentares/views.py
  sapl/templates/parlamentares/mandato_form.html
Labels: bug

#3113 Chamado 661236 - Tipo Leitura e Resultado em Extrato
  sapl/sessao/views.py
  sapl/templates/sessao/adicionar_varias_materias_expediente.html
Labels: bug
